services:
  - postgresql

language: python

python:
  - "3.7"

before_script:
  - psql -c 'create database factory_simulator;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - flake8
  - coverage erase
  - python manage.py makemigrations
  - python manage.py migrate
  - pytest --cov

after_success:
  - pip install codecov
  - codecov
