apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: a2lsdGhhcg==
  POSTGRES_PASSWORD: QmVzdHVzZXJzZG9udGxvc2VwYXNzd29yZHNidXRtYXlmb3JnZXR0aGVtZWFzaWx5MTIz
